### ISSUE TITLE
Why the target is set to esnext and the lib to es6?

### ISSUE THREAD

**Issue by Hatko** [react-native-community/react-native-template-typescript#136]
# Question

In our team, we're trying to mimic the `tsconfig` you created. Did you have any reasoning behind setting these particular versions for `target` (esnext) and `lib`(es6)?

**Comment by radko93** [comment]
There is no much behind it, as this is only being used for type checking.

**Comment by Hatko** [comment]
@radko93 I see 🙂

`esnext` provides more features, which are not necessarily available for `es6` (`flatMap` on an array, for example). Moreover, as I understand, the compiler will make `esnext` version anyway, as it's specified for the target. 
That's why I'm curious why they aren't both set to `esnext`. 

If there is no difference, would it make sense to make it consistent?

**Comment by radko93** [comment]
I think it can be set to `esnext`, feel free to open a PR. It makes no difference because it's Metro bundler and babel that actually transpile the code.

**Comment by LinusU** [comment]
The reason why target and lib is set to different is because Metro will use Babel to transpile the _syntax_, which is what `target` controls.

On the other hand, `lib` specifies which part of the standard library exists, which isn't handled by Babel.

e.g. `"syntax": "esnext"` will allow you to use `async function` and `await`, which Babel can transpile. On the other hand, `"lib": "esnext"` will allow you to use `BigInt`, which will then fail at runtime because `BigInt` isn't supported...
