### ISSUE TITLE
VirtualizedList Error | TypeError: Cannot read property 'updateCellsBatchingPeriod' of undefined 

### ISSUE THREAD

**Issue by ammoradi** [react-native-community/react-native-template-typescript#152]
# VirtualizedList Error

I don't know its this lib's bug or the react-native because of this I created a Question type issue.
There is a bug with SectionList/VirtualizedList when I'm using this template.
I described all things about the bug here **[[TypeScript][SectionList] TypeError: Cannot read property 'updateCellsBatchingPeriod' of undefined](https://github.com/facebook/react-native/issues/29437)** and I also provide screenshots and test repo.
Please help me if this is your bug.

**Comment by emin93** [comment]
Seems like you managed to resolve the issue, that's why I'm closing this ticket.

If you didn't: This can't be a TypeScript bug as it is happening runtime. Babel is being used to transpile TypeScript files, so it should happen with plain JavaScript as well. Try to create a new project with the latest version (there have been a few hotfixes which might have fixed this issue).

**Comment by liplylie** [comment]
For me, ammoradi's solution did not work.

What I did was modify `node_modules/react-native/Libraries/Lists/VirtualizedList.js`, and add `this.props = props` inside of the constructor:

```  
   constructor(props: Props, context: Object) {
    super(props, context);
    this.props = props;
```
