### ISSUE TITLE
Typescript compiler

### ISSUE THREAD

**Issue by saihaj** [react-native-community/react-native-template-typescript#160]
I am trying to figure out why TypeScript compiler doesn’t work https://github.com/ShabadOS/mobile/issues/65 and ended up on [StackOverflow Answer](https://stackoverflow.com/a/60743765/11321732) and it makes it makes sense why typechecking doesn’t work out of the box.

### Question
Can I get rid of Babel and use TypeScript compiler? Why does this template not use TypeScript compiler?

**Comment by emin93** [comment]
You are probably looking for the [React Native TypeScript Transformer](https://github.com/ds300/react-native-typescript-transformer).

> Why does this template not use TypeScript compiler?

Originally it used the TypeScript Transformer mentioned above, but since Babel 7 has been included into RN, it is not required anymore. You can still do type checking by running `tsc`.
