### ISSUE TITLE
Support RN 0.64 preview 

### ISSUE THREAD

**Issue by willmayn** [react-native-community/react-native-template-typescript#174]
## Expected results

There should be a template that supports typescript with RN 0.64 preview versions.

## Observed results

There is not currently a typescript template which supports react native 0.64 preview versions. If you try to specify the preview version of RN 0.64 and the typescript template at the same time, the template overwrites the 0.64 preview version and instead uses 0.63. 

This is the command I ran which yielded these results:
> npx react-native init RN064 --version 0.64.0-rc.1 --template react-native-template-typescript --npm

**Comment by willmayn** [comment]
My team is trying to migrate to the new React Native Windows preview version, and their recommended upgrade story is to create a new RN project on the preview version and migrate over your source from there since they do not have a react-native-upgrade-helper yet. However, our project is based in typescript and so the lack of 0.64 preview typescript template support is making it much harder to upgrade the project.

https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.64.0-preview.1

**Comment by emin93** [comment]
There is no support for Beta & Release Candidate versions of React Native, yet. Feel free to create a PR if you want this added. Though I think this will also involve pipeline adjustments because of the required npm beta tag.

But I'm confident that this template will support 0.64 as soon as it's out, so you might as well have some patience.
