### ISSUE TITLE
support react native 0.64.0 

### ISSUE THREAD

**Issue by stfenjobs** [react-native-community/react-native-template-typescript#192]
## Expected results

What did you expect to happen?
support react native 0.64.0 

## Observed results

What happened?
react-native has been released 0.64.0  https://github.com/facebook/react-native/releases
### Logs

Please add the log output here.

**Comment by Ahmdrza** [comment]
I upgraded myself using `yarn upgrade --latest` and updated `minSdkVersion` to 21. It updated React and RN to the latest.

**Comment by tlawork** [comment]
I am running RN 0.64.0 and I just pulled the latest template from this repo, then ran yarn, then yarn android - and I am getting an exception at startup:  MyApp has not been registered. This can happen if.... metro is running from the wrong server..... and so forth.

Actually I'm not sure it is kicking off a metro server - normally with the default react-native template - it pops up a command window for the metro server - but this is not in this case.  I dont know if this is related to the new 0.64.0 version - but I'm putting my experience here in case it helps.  I will keep the project in this state if more data needed - but otherwise I'm reverting to default template for now.

_(if this exception is caused by some other known issue - then please disregard)_
