### ISSUE TITLE
Add 0.65.2 support for template

### ISSUE THREAD

**Issue by likern** [react-native-community/react-native-template-typescript#232]
Allow to create RN app with version `0.65.2`

**Comment by emin93** [comment]
This has been open for quite some time now. Due to the setup of this repo and the small amount of active contributors, I don't see us maintaining multiple React Native versions.

What you could do is creating an app with `0.65.1` using `npx react-native init MyApp --template react-native-template-typescript@6.7.1` and then updating manually to `0.65.2`. The update effort is low: https://react-native-community.github.io/upgrade-helper/?from=0.65.1&to=0.65.2
